[project]
name = "backend"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"

[contracts.new-options-nft]
path = "contracts/options-nft.clar"

[contracts.redstone-verify]
path = "contracts/redstone-verify.clar"

[contracts.traits]
path = "contracts/traits.clar"

[contracts.vault]
path = "contracts/vault.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
