[project]
name = 'backend'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'
requirements = []

[contracts.options-nft]
path = 'contracts/options-nft.clar'
clarity_version = 1

[contracts.redstone-verify]
path = 'contracts/redstone-verify.clar'
clarity_version = 1

[contracts.traits]
path = 'contracts/traits.clar'
clarity_version = 1

[contracts.vault]
path = 'contracts/vault.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
